// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_lll96DYJSbUdLmqaal_O054Eyy0xPs',
    appId: '1:768052448622:web:75886e1a0ee9772c00457f',
    messagingSenderId: '768052448622',
    projectId: 'clima-93ade',
    authDomain: 'clima-93ade.firebaseapp.com',
    storageBucket: 'clima-93ade.firebasestorage.app',
    measurementId: 'G-YSGRNY2ZB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4lhatVLjwU9_8BqNTuOHlWXumYRBzghU',
    appId: '1:768052448622:android:b0d1a791fb51ee3a00457f',
    messagingSenderId: '768052448622',
    projectId: 'clima-93ade',
    storageBucket: 'clima-93ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeacPo42DPFarMGOSNog2U63L08a1mnA',
    appId: '1:768052448622:ios:f43965e3bdcb223400457f',
    messagingSenderId: '768052448622',
    projectId: 'clima-93ade',
    storageBucket: 'clima-93ade.firebasestorage.app',
    iosBundleId: 'com.gammagamma.clima.clima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeacPo42DPFarMGOSNog2U63L08a1mnA',
    appId: '1:768052448622:ios:f43965e3bdcb223400457f',
    messagingSenderId: '768052448622',
    projectId: 'clima-93ade',
    storageBucket: 'clima-93ade.firebasestorage.app',
    iosBundleId: 'com.gammagamma.clima.clima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT_lll96DYJSbUdLmqaal_O054Eyy0xPs',
    appId: '1:768052448622:web:e51c0873c2007fb300457f',
    messagingSenderId: '768052448622',
    projectId: 'clima-93ade',
    authDomain: 'clima-93ade.firebaseapp.com',
    storageBucket: 'clima-93ade.firebasestorage.app',
    measurementId: 'G-CWRTHH3XGE',
  );
}
